language: node_js
node_js:
  - "12.16.3"
install:
  - npm install
cache:
  directories:
    - "node_modules"
script:
  - npm test
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
